name: Deploy to Kubernetes

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: your-dockerhub-username/web-app
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./app
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig.yaml
        export KUBECONFIG=$PWD/kubeconfig.yaml
        kubectl version

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s-deployment/deployment.yaml
        kubectl apply -f k8s-deployment/service.yaml